import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { CreateProjectCommand } from '../commands/create-project.command';
import { Inject } from '@nestjs/common';
import { ProjectRepository } from '../ports/project.repository';
import { Project } from '../../domain/project.entity';

import { EventPublisher } from '@nestjs/cqrs';

@CommandHandler(CreateProjectCommand)
export class CreateProjectHandler
  implements ICommandHandler<CreateProjectCommand>
{
  constructor(
    @Inject('ProjectRepository')
    private readonly projectRepository: ProjectRepository,
    private readonly publisher: EventPublisher,
  ) {}

  async execute(command: CreateProjectCommand): Promise<Project> {
    const rawProject = new Project(
      '', // ID will be generated by Repo or we should generate it here if we want to include it in event before save?
      // Mongoose usually generates ID. If we want ID in event, we usually need it before.
      // But `projectRepository.create` returns the saved project with ID.
      command.title,
      command.description || '',
      'active',
      [],
      false,
      {},
      {},
      0,
      { todo: [], inProgress: [], done: [] },
      [],
      [], // logs
      new Date(),
      new Date(),
    );

    // Save first to get ID
    const savedProject = await this.projectRepository.create(rawProject);

    // Merge context and apply event
    const project = this.publisher.mergeObjectContext(savedProject);

    // We need userId here! But Command doesn't have it explicitly in the signature shown.
    // CreateProjectCommand probably needs userId.
    // Let's check CreateProjectCommand.
    project.created(command.userId || 'system');
    project.commit();

    return savedProject;
  }
}
