import type { Metadata } from "next";
import { Geist, Geist_Mono, Rajdhani, Playfair_Display, Dancing_Script } from "next/font/google";
import { Toaster } from "sonner";

import { PresenceTracker } from "@/features/presence/components/PresenceTracker";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rajdhani = Rajdhani({
  variable: "--font-rajdhani",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rajdhani.variable} ${playfair.variable} ${dancingScript.variable} antialiased`}
      >
        {children}
        <PresenceTracker />
        <Toaster theme="dark" position="bottom-right" />
      </body>
    </html>
  );
}
