export enum ErrorCode {
    // Common
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
    CONFLICT = 'CONFLICT',

    // Database
    DB_DUPLICATE_KEY = 'DB_DUPLICATE_KEY',
    DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',

    // Custom Domain Errors
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
}
