export enum MoodType {
  HAPPY = 'happy',
  SAD = 'sad',
  NEUTRAL = 'neutral',
  JOY = 'joy',
  CALM = 'calm',
  INSPIRED = 'inspired',
  STRESSED = 'stressed',
  LONELY = 'lonely',
  ANGRY = 'angry',
  ENERGETIC = 'energetic',
  EMPTY = 'empty',
  FOCUSED = 'focused',
  ANXIOUS = 'anxious',
  TIRED = 'tired',
}
